#!/usr/bin/ruby

# Generate pages for each Party

require 'json'
require 'yaml'

people  = JSON.parse(File.read('_data/people.yaml'))
parties = JSON.parse(File.read('_data/parties.yaml'))

parties.each do |party|
  filename = "party/#{party['id']}.md"

  data = {
    "layout" => 'party',
    "id" => party['id'],
    "name" => party['name'],
    "autogenerated" => true,
  }
  text = data.to_yaml + "---\n"
  warn "Writing #{filename}"
  File.write(filename, text)
end
