#!/usr/bin/ruby

# Generate pages for each Party

require 'json'
require 'yaml'
require 'parallel'

@parties = JSON.parse(File.read('_data/parties.yaml'))

ps = ARGV[0].nil? ? @parties : @parties.select { |p| p['id'] == ARGV[0] }
warn "Operating on #{ps.count} parties"

Parallel.each(ps, :in_threads => 5) do |party|
  filename = "party/#{party['id']}.md"
  warn "Processing #{party['id']} to #{filename}"

  data = {
    "layout" => 'party',
    "id" => party['id'],
    "title" => party['name'],
    "autogenerated" => true,
  }
  text = data.to_yaml + "---\n"
  File.write(filename, text)
end
