#!/usr/bin/ruby

# Generate pages for each Person

require 'json'
require 'yaml'

@people  = JSON.parse(File.read('_data/people.yaml'))
@parties = JSON.parse(File.read('_data/parties.yaml'))

def dates(membership)
  return "" unless membership['start_date'] || membership['end_date']
  return [membership['start_date'], membership['end_date']].map {|s| s && s[0,4] }.join " – ".strip
end

def memberships(mp)
  mp['memberships'].map { |m|
    party = @parties.detect { |p| p['id'] == m['organization_id'] } || next
    {
      "id" => m['organization_id'],
      "name" => party['name'],
      "start" => m['start_date'],
      "end" => m['end_date'],
    }
  }.reject(&:nil?)
end


@people.each do |mp|
  filename = "person/#{mp['id']}.md"
  warn "Writing #{filename}"

  data = {
    "layout" => 'mp',
    "id" => mp['id'],
    "name" => mp['name'],
    "memberships" => memberships(mp),
    "autogenerated" => true,
  }
  text = data.to_yaml + "---\n"
  warn text
  File.write(filename, text)
end
