#!/usr/bin/ruby

# Generate pages for each Issue

require 'json'
require 'yaml'
require 'parallel'

@data = JSON.parse(File.read('_data/issues.yaml'))

es = ARGV[0].nil? ? @data : @data.select { |e| e['id'] == ARGV[0] }
warn "Operating on #{es.count} entries"

Parallel.each(es, :in_threads => 5) do |e|
  filename = "issue/#{e['id']}.md"
  warn "Processing #{e['id']} to #{filename}"

  data = {
    "layout" => 'issue',
    "id" => e['id'],
    "title" => e['text'],
    "html" => e['html'],
    "autogenerated" => true,
  }
  text = data.to_yaml + "---\n"
  File.write(filename, text)
end
