#!/usr/bin/ruby

# Generate pages for each Person

page = <<eos
---
layout: mp
id: ID
name: NAME
autogenerated: true
---
eos

require 'json'

filename = ARGV.first || "_data/people.yaml"
JSON.parse(File.read(filename)).each do |mp|
  text = page.gsub(/ID/, mp['id']).gsub(/NAME/, mp['name'])
  filename = "person/#{mp['id']}.md"
  warn "Writing #{filename}"
  File.write(filename, text)
end
